[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run dashboard.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"